version: '3.4'
 
networks:
    bankapp:       
 
services:
    db:
        #container_name: dbContainer
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        #image: pizza_example_db
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    api:
        #container_name: apiContainer
        image: apidb-dockerdemo:1.2
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: API/Dockerfile
        depends_on:
            - db
